name: .NET

on: [push]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      - name: welcome
        run: echo "Hello guys"
      - name: build 
      - run: dotnet build ActionsKata